### ISSUE TITLE
Define the datastructure of a Batch in such a way that it can be split into Tasks

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-WebService#24]
How do we handle inputs?

How do we handle executables?

Make sure to have arguments for the choice

- [x] In which ways could input be handled?
- [x] In which ways could executables be handled? (Maybe keep in mind that this method should be substituted by virtual machines later)

**Comment by Kaliahh** [comment]
### Conclusion 

A Batch will be a string containing the source code and a list of strings consisting of inputs

**Comment by naitoarekkus** [comment]
It is done, therefore i close
