### ISSUE TITLE
FileDownloadController should implement authorisation

### ISSUE THREAD

**Issue by AxialDark** [P7-Team/P7-WebService#73]
FileDownloadController currently allow authenticated users to download all files on the system.
This needs to be changed such that allocated users can download files for tasks and only the owner of the batch can download the results of the batch.

The username of the user making the request can be extracted from the HttpContext.
Check UserController for example of how to do this.

**Comment by AxialDark** [comment]
Ser fint ud

**Comment by zaztz** [comment]
Det ser fint ud

**Comment by AxialDark** [comment]
Reviewed, lukker task
