### ISSUE TITLE
Setup the web-service project to be ready for TDD

### ISSUE THREAD

**Issue by naitoarekkus** [P7-Team/P7-WebService#8]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The Python web-service project has been setup, such that all new and existing tests can be run with minimal effort.
By minimal effort in best case is to run a single script.
Also a very brief description of the necessary structure of the project to get the test solution to work (help the other developers to use the structure).

**Describe alternatives you've considered**
There is the builtin testing functionality in Python.
Else we have also talked about using pytest.

**Additional context**
There might already have been something setup, but please check.

**Comment by soenderby** [comment]
Created project named WebService-UnitTests, containing a single test, that was run successfully by the CI workflow.
